name: GESPRO_G1_E3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - click=8.2.1
  - expat=2.7.3
  - flask=3.1.2
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - ncurses=6.5
  - openssl=3.0.18
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.1
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - werkzeug=3.1.3
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
prefix: /home/racha/anaconda3/envs/GESPRO_G1_E3
